# Generated by Django 5.0.3 on 2024-04-01 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_movie_country_movie_extra_data_movie_release_year"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMoviePreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferences",
                    models.JSONField(
                        default=dict,
                        help_text="Stores user preferences for movies like genres, directors, etc.",
                    ),
                ),
                (
                    "watch_history",
                    models.JSONField(
                        default=list,
                        help_text="Stores information about movies the user has watched.",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
