# Generated by Django 5.0.3 on 2024-04-02 20:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_usermoviepreferences"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="movie",
            unique_together={("title", "country", "release_year")},
        ),
    ]
